### ISSUE TITLE
UI issue summary

### ISSUE THREAD

**Issue by odeinjul** [Life-USTC/Life-USTC#24]
Reported UI issues here will be fixed together periodically.

**Comment by odeinjul** [comment]
* DatePicker in HomeView frame size mismatch.

**Comment by tiankaima** [comment]
![image](https://github.com/Life-USTC/Life-USTC/assets/91816094/26eb98b2-3987-4920-8cfc-bc68e1593f6f)

Just checking, is this really the way you want ExamPreview to look like? Looks too much space to me.

**Comment by tiankaima** [comment]
1. In HomeView, when date isn't set to today, display today as that date's representation, like mm/dd
2. In HomeView, the refreshable function should be rather force updating, trigger forceUpdate there.
3. In ExamView, show a text like "no more exam" or some design like ExamPreview instead of just empty
4. In ClassRoomView, show timing hints at the top to indicate user when the room is empty or not
	> comment on this: how about we make the bar movable and show what time the bar represents? I don't think we have enough space on the top to make it clear

**Comment by tiankaima** [comment]
Stepping further, consider tightening front-back end relationship with models like RxSwift that uses MVVM models, which we have already part-way implemented in many views.

The absence of real `ViewModel` would make it harder for showing progress in controller. This could be easily handled with `Combine` framework to strengthen the model.

The `@Binding AsyncViewStatus` way seems a bit tedious in many implementations, and shall be deprecated gradually with more formally written `Publisher<AsyncViewStatus>` as a more suitable way to receive updates on asynchronous events.

Further discussions are still required after the first example is given, which I hope wouldn't be that troublesome...

**Comment by tiankaima** [comment]
* Add the ability to chose which website to use Reeder
* Add a view for user to pick its label for TPNS to push

**Comment by odeinjul** [comment]
* Incomplete display when more than 6 exams -> need more paddings.

**Comment by tiankaima** [comment]
> * Incomplete display when more than 6 exams -> need more paddings.

Just want to point out the padding absolutely sucks, might as well just change back to the old way of using `TabView`, now it's visually incomplete.
<img width="464" alt="image" src="https://github.com/Life-USTC/Life-USTC/assets/91816094/98d12f46-5b6b-464b-87f7-b710b0af5bc7">

But frankly, I don't know the swiftUI-way of doing this without using Introspect to inject spacer in every `ScrollView`

**Comment by odeinjul** [comment]
I thought ```.padding(30)``` meaning adding the **absolute** space for the tab bar (approximate 30), rather than a relative space relating with _the number of your exams_ or _etc_.

**Comment by tiankaima** [comment]
> I thought `.padding(30)` meaning adding the **absolute** space for the tab bar (approximate 30), rather than a relative space relating with _the number of your exams_ or _etc_. That is there should be a enough and fixed space for the tab bar at any time.

see 37e7d81fd3ee47b91f053c6803a5873b9c6f0216, case closed for this.

* Overlapping:
<img width="450" alt="image" src="https://github.com/Life-USTC/Life-USTC/assets/91816094/2dfa80f2-550d-4fc2-a735-d4e9a8277ed7">

* With a bit more scroll:
<img width="473" alt="image" src="https://github.com/Life-USTC/Life-USTC/assets/91816094/dfe6ffe7-678a-4b53-bf14-95d228b46b1e">

Just add Spacer() instead of padding, the original idea is a Rounded Rectangle above the view, not under the view...
